[env]
TERM = "xterm-256color"

[font]
size = 11

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[general]
#import = ["/home/philip/.config/alacritty/base16_default_dark.toml"]
import = ["rose-pine-theme.toml"]
live_config_reload = true

[selection]
save_to_clipboard = true

#[cursor.style]
#shape = "Block"

[window.padding]
x = 8
y = 8
