[colors.primary]
background = '#191724'
foreground = '#e0def4'

[colors.selection]
text = '#e0def4'
background = '#26233a'

[colors.cursor]
text = '#191724'
cursor = '#c4a7e7'

[colors.normal]
black   = '#26233a'
red     = '#e95c48'
green   = '#6ed677'
yellow  = '#dadb7b'
blue    = '#a672dd'
magenta = '#9886ad'
cyan    = '#c4a7e7'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e06c5f'
green   = '#86e08d'
yellow  = '#e7e897'
blue    = '#e8c6ff'
magenta = '#8f72cc'
cyan    = '#9971b5'
white   = '#ffffff'
